apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
  - istio-virtualservice.yaml
  - istio-destinationrule.yaml
  - istio-gateway.yaml
configMapGenerator:
  - name: env-config
    literals:
      - DOMAIN=example.com  # Default value, overridden later
replacements:
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.DOMAIN
    targets:
      - select:
          kind: VirtualService
          name: python-web-vs
        fieldPaths:
          - spec.hosts.0
      - select:
          kind: Gateway
          name: python-web-gateway
        fieldPaths:
          - spec.servers.0.hosts.0