apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
  - istio-virtualservice.yaml
  - istio-destinationrule.yaml
  - istio-gateway.yaml
configMapGenerator:
  - name: env-config
    files:
      - env.yaml
vars:
  - name: DOMAIN
    objref:
      kind: ConfigMap
      name: env-config
      apiVersion: v1
    fieldref:
      fieldpath: data.DOMAIN